### ISSUE TITLE
[conversationgames] error with reply component

### ISSUE THREAD

**Issue by mrPauwHaan** [japandotorg/Seina-Cogs#22]
Conversationgames makes use of replying of the initial command. However, the problem with this is that this results in an error when using scheduled commands with cogs like FIFO.

Therefore, I would be nice when the cog cannot find the initial command it still sends a message but without it being a reply. Instead of sending an error.

**Comment by japandotorg** [comment]
@mrPauwHaan hello I've implemented so that if message reference is none the bot should use `ctx.send` instead of `ctx.reply`

**Comment by mrPauwHaan** [comment]
Thank you!
